# Generated by Django 5.0.3 on 2024-12-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=150)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
